### ISSUE TITLE
Have profile cards display the saved characters

### ISSUE THREAD

**Issue by branchwag** [branchwag/character-generator#175]
Cal and LeAnne tag teaming on this one. The profile cards need to show the user's saved character details so the user can then click on each one and get the correct output. Sam is writing the DB storage part so we have an endpoint to go fetch this data from. We will just need to display it on the card. Character name on card and maybe even thumbnail of the generated image if we can? 

http://localhost:3001/profile

![Image](https://github.com/branchwag/character-generator/assets/29187461/09f39986-86b1-4b2c-80e4-04e6fd879634)

**Comment by croberts27** [comment]
Got this completed!
